### ISSUE TITLE
[PE-D][Tester E] User guide unclear edit command

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2113T-T09-3/tp#153]
User guide did not specify that the order of n/ q/ p/ d/ must be followed **strictly**

Input: edit 4 p/100.00 q/05

Expected output: Product details have been updated.

Actual output: Invalid format. For more information on the commands, use `help`.

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: rexyyong/ped#8

**Comment by Kobot7** [comment]
User guide did specify that parameters must be in specified order. Link to section "Notes about the Command Format": https://ay2324s2-cs2113t-t09-3.github.io/tp/UserGuide.html#features

However, noted that the section is not obvious enough and will consider making it a section instead of sub-section.
